### ISSUE TITLE
System.ComponentModel.Win32Exception (8): Exec format error

### ISSUE THREAD

**Issue by piotrintes** [Rfvgyhn/min-ed-launcher#31]
`
[23:34:26 INF] Checking for updates
[23:34:28 INF] Available Products:
        Elite Dangerous: Horizons FORC-FDEV-D-1013 Up to Date
        Elite Dangerous           FORC-FDEV-D-1010 Up to Date
        Elite Dangerous: Arena    FORC-FDEV-D-1012 Up to Date
[23:34:28 INF] Launching Elite Dangerous: Horizons
[23:34:28 ERR] Couldn't start selected product: System.ComponentModel.Win32Exception (8): Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MinEdLauncher.Product.run(FSharpOption`1 proton, String args, RunnableProduct product)
`

Everything was working fine (last played today, about an hour ago), until latest steam update. Now I'm getting this error. I've tried several proton versions:
- Proton Experimental (one I was using successfuly before)
- 6.3
- 5.0-10
- 4.11-13

I've checked the prefix (it runs until failed login because no launcher).

Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2
Kernel Version: 5.8.0-55-generic
OS Type: 64-bit

**Comment by Rfvgyhn** [comment]
This looks like the [reaper](https://github.com/Rfvgyhn/min-ed-launcher/issues/26) [issue](https://github.com/Rfvgyhn/min-ed-launcher/issues/30). Which version of the launcher are you using? I just released v0.5.2 which is supposed to take care of that.

**Comment by piotrintes** [comment]
I updated before writing there. Unfortunetly it didn't fix the issue.

**Comment by piotrintes** [comment]
ERROR: ld.so: object '/home/piotr/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[23:51:55 INF] Elite Dangerous: Minimal Launcher - v0.5.2
[23:51:56 INF] Elite Runtime
    Platform: Steam
    CobraBay Version: 0.4.6709.0
    Products Dir: /home/piotr/.steam/debian-installation/steamapps/common/Elite Dangerous/Products
[S_API] SteamAPI_Init(): Loaded '/home/piotr/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 359320

This is how the header looks like.

**Comment by Rfvgyhn** [comment]
Can you post a full log entry from `logs/min-ed-launcher.log`?

**Comment by piotrintes** [comment]
[min-ed-launcher.log](https://github.com/Rfvgyhn/min-ed-launcher/files/6627108/min-ed-launcher.log)

**Comment by Rfvgyhn** [comment]
Not sure how 0.5.2 runs on my machine, but had I not been too lazy to write a proper unit test, this would have been caught. I should have a fix for this shortly.

**Comment by piotrintes** [comment]
Good to hear that :-)
